//prettier-ignore
export const CHANGE_DEVICE_TO_SMALL_PHONE = 'CHANGE_DEVICE_TO_SMALL_PHONE';
export const CHANGE_DEVICE_TO_MEDIUM_PHONE = 'CHANGE_DEVICE_TO_MEDIUM_PHONE';
export const CHANGE_DEVICE_TO_LARGE_PHONE = 'CHANGE_DEVICE_TO_LARGE_PHONE';
export const CHANGE_DEVICE_TO_TABLET = 'CHANGE_DEVICE_TO_TABLET';
export const CHANGE_DEVICE_TO_PORTRAIT_TABLET =
  'CHANGE_DEVICE_TO_PORTRAIT_TABLET';
export const CHANGE_DEVICE_TO_LANDSCAPE_TABLET =
  'CHANGE_DEVICE_TO_LANDSCAPE_TABLET';
export const CHANGE_DEVICE_TO_DESKTOP = 'CHANGE_DEVICE_TO_DESKTOP';
